### ISSUE TITLE
Can we use Laravel Sail to work with this project locally?

### ISSUE THREAD

**Issue by jigar-dhulla** [MrPunyapal/basic-crud#24]
https://github.com/mr-punyapal/basic-crud/blob/c48ff270d7da92b8c2eb73a475c1d47cce02a2d5/composer.json#L20C1-L21C1

**Comment by MrPunyapal** [comment]
can you make PR with an optional usage of sail? 🤔

I mean I don't know if we can...

**Comment by jigar-dhulla** [comment]
- If we are not using sail, you can remove that package from dependency.
- I will try to add sail support.
